dist: xenial
language: cpp
compiler: clang
before_script:
- sudo apt-get update -qq
- sudo apt install libboost-test-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:

  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: master
  
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uarcsigov:$BINTRAY_API_KEY "https://api.bintray.com/content/arcsigov/otus-homework/homework/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=i386,amd64;publish=1"
